<?php

/**
 * @file
 * File module ducumentation.
 */

/**
 * Implements hook_page_attachments().
 */
function custom_product_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'custom_product/custom-product';
}

/**
 * Implements hook_form_alter().
 */
function custom_product_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'update_products') {
    $form['actions']['submit']['#value'] = t('Update Product');
  }

  if ($form_id == 'create_product') {
    $form['actions']['submit']['#value'] = t('Create Product');
  }
}

if (!function_exists('custom_product_dd')) {

  /**
   * Implements function dd(). We use dd() for debugging.
   */
  function custom_product_dd($parameter) {
    echo "<pre>";
    print_r($parameter);
    echo "</pre>";
    die();
  }

}
